repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        exclude: pupil_recording_interface/externals
        args: ['--ignore=E203,W503,W504']
