repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.0.4
    hooks:
    -   id: isort

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: ['--ignore=E203,W503,W504']
        exclude: docs/conf.py
