# Config file for automatic testing at travis-ci.org
os: linux
dist: bionic
language: python

jobs:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=minimal
    - python: 3.7
      env: TOXENV=latest
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=lint
    - env: CONDA_BLD_PATH=~/conda-bld
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install conda-build anaconda-client
        - conda config --set anaconda_upload no
      script:
        - conda build -c conda-forge -c RoboStack -c phausamann ci/conda_recipe
      after_success:
        - chmod +x ci/conda_recipe/conda_upload.sh

# Command to install build system dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

deploy:
  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt --add deploy.password
  # Paste the hashed password in the `secure` field
  - provider: pypi
    distributions: sdist bdist_wheel
    username: phausamann
    password:
      secure: cRtfmsupJcyrZ1EU+NJ1eng0Abn9LeDVHLf1xZ1/1sg3qq6PwJwxNFJHTMin0sIJXERFAGG3btRnFqiwYsrxF7OdWObDYZN3G9riKKhS2Z5bSanWyrQk4XF/s9haONHKv2falsZ6nnux9GDMod+ojPzedNGagISLsLixHMRZmYFnUAJtdzDOm6PoNTui0+0C3bHoAIPu+FZJ1rPV1xmGM+4YGLg/j3yFt6SIY0XYY9d2torXSwD1E0+8V/kPxTcyNCQVE9LlFP3v9xLt2wYq7ehjGbetehSZyJxjchjtgABBMBkGTKqBwb3pgagaRmC9KVatpRVVVSLJRZAbFOmfK3QkZzrVzDVwOEloVhhUxUAm3rZDbZHmvHO0maS5VkpDAb3lE1edLziLiD0qqLBSuy5Tru+uELa6IO6gO8r/dA8usnKAcNWHIjrpLd3W7P+btjrmrSx8ReYs9PitKFiCLgleoAJGZFoSN0sOIAimCzvIsCvJyjlbHOvDyb+ziqvxu66yz/hBmupGibIT2529pyVW713gBOyrIvsLqzX3uDw6aYMTSi4aYp5+sfkCA5RE8Fc6PEPnqj6LbWjBF6bgelj3wUc9J4ZniuSWFMDKmBhk/p/j9CRg7RYQ5g+lK5E0oJma0vThqx8MKDivVk4oOMD8txcA0g1DJn8oE6i4ptc=
    on:
      tags: true
      repo: phausamann/rigid-body-motion
      python: 3.7
    skip_cleanup: true
  # Install anaconda client, then run:
  # $ anaconda auth -c -n travis --url https://anaconda.org/<username> --scopes "api:write api:read"
  # and add the generated token as $ANACONDA_TOKEN to the repo's env variables
  # on travis
  - provider: script
    script: ci/conda_recipe/conda_upload.sh
    on:
      tags: true
      repo: phausamann/rigid-body-motion
      condition: "$CONDA_BLD_PATH = $HOME/conda-bld"
    skip_cleanup: true
