# Config file for automatic testing at travis-ci.com
os: linux
dist: bionic
language: python

jobs:
  include:
    - env: CONDA_BLD_PATH=~/conda-bld RBM_ROS_DEBUG=true
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -c conda-forge boa anaconda-client
        - conda config --set anaconda_upload no
        - conda config --add channels robostack
        - conda config --add channels conda-forge
      script:
        - conda mambabuild ci/conda_recipe
      after_success:
        - chmod +x ci/conda_recipe/conda_upload.sh
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=minimal
    - python: 3.7
      env: TOXENV=latest
    - python: 3.6
      env: TOXENV=docs
      install:
        - apt-get install pandoc
    - python: 3.6
      env: TOXENV=lint

# Command to install build system dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

deploy:
  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt --com deploy.password
  # Paste the hashed password in the `secure` field
  - provider: pypi
    distributions: sdist
    username: phausamann
    password:
      secure: "tSq7XQWOlDhRpOnHnZ8QWJSew0VUT68i8YEqFcyghFGSgrzJhGkOLl2Fx11f0wXGY2BWom4Dpj82LJI5vJt8YyhDtrkbQnVw8z9uS1eWPmW4WOAuY6kQQogt84EU7F0rJSmQWTHc5GQYNfkqyYLxoJXhvq6Y9KvZ8fZyKwrsUJwpz9aBzu59JYu6YnvSE1/GRf2TVOCcYSaCJisNoZUdalQFUB+QBtVMOuMugp5zPCucfsovEFni94i9PW0OOMF6ZUMiwbsUGHAeFSSETGWB16FWjh8HlXq5eZk4NXi0GCwineI8/4DLvP7Qtipw68AeMi2IUPuUV81GOVzMkaccivXdLfxq58bzB0XKHWZ+OYUhK1C5gG3gfzUAyxFaP2Mr+SWWnboB6tNnHZXevhzyd3g+MbJVE7Oz0aIDaPJuwtDlkqPAQK2UtnQi1xxHpvyZmLYJalayPsOrsaWQ40XpRGARmCICeToHDwmoSRlqlrw7kVrJYS250ei170oSgQFiMWTE+/RguusCvm7pj4clAoLlqgz6WxftXNUwpPfPOmn9A9fxFWHAHe/T74HDpbL97p2Uu7C7jjz7mjoGHizninUVLiYAFKu6eLy9IBqesI1hCx9IBg3ySSRDz+UfADL8iL2qUR/e3NhzAoJIZ1qHURYHltY9sY+KXDcf9PbnWc0="
    on:
      tags: true
      repo: phausamann/rigid-body-motion
      condition: "$TOXENV = py36"
    skip_cleanup: true
  # Install anaconda client, then run:
  # $ anaconda auth -c -n travis --url https://anaconda.org/<username> --scopes "api:write api:read"
  # and add the generated token as $ANACONDA_TOKEN to the repo's env variables
  # on travis
  - provider: script
    script: ci/conda_recipe/conda_upload.sh
    on:
      tags: true
      repo: phausamann/rigid-body-motion
      condition: "$CONDA_BLD_PATH = $HOME/conda-bld"
    skip_cleanup: true
