name: rigid-body-motion
channels:
  - conda-forge
dependencies:
  - python=3.6.5
  - pip=19.1.1
  - numpy=1.16.3
  - scipy=1.3.0
  - pandas=0.24.2
  - xarray=0.12.1
  - quaternion=2019.3.18.14.33.20
  - numba=0.43
  - pygments=2.4.0
  - pytest=4.5.0
  - pytest-runner=4.4
  - pytest-cov=2.7.1
  - sphinx=1.8.5
  - sphinx_rtd_theme=0.4.3
  - numpydoc=0.9.1
  - coverage=4.5.3
  - bumpversion=0.5.3
  - flake8=3.5.0
  - tox=3.5.2
  - twine=1.12.1
  - pip:
    - watchdog==0.9.0
    - anytree==2.6.0
