name: rbm-ros
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - quaternion
  - numba
  - pygments
  - pytest
  - tox
  - virtualenv
  - sip
  - pip:
    - rospkg
    - anytree
