name: rbm
channels:
  - defaults
  - conda-forge
  - robostack
dependencies:
  - python=3.8
  - pip=21.1
  - numpy=1.21
  - scipy=1.7
  - pandas=1.3
  - xarray=0.20
  - netcdf4=1.5
  - quaternion=2021.10.7.23.40.37
  - numba=0.53
  - anytree=2.8
  - pooch=1.3
  - pytest=6.2
  - pytest-cov=2.12
  - sphinx=4.0
  - sphinx_rtd_theme=0.5
  - nbsphinx=0.8
  - pandoc=2.16
  - numpydoc=1.1
  - sphinx-autosummary-accessors=0.2.1
  - matplotlib=3.5
  - jinja2=2
  # ROS dependencies
  - ros-noetic-rospy
  - ros-noetic-tf
  - ros-noetic-tf2-ros
  - ros-noetic-tf2-geometry-msgs
  - ros-noetic-geometry-msgs
  - ros-noetic-visualization-msgs
  - python-orocos-kdl=1.4.0
  - boost=1.74
  - ipywidgets
  - pip:
      - --editable .
