name: rbm
channels:
  - conda-forge
  - RoboStack
  - phausamann
dependencies:
  - python=3.6
  - pip=19.1
  - numpy=1.18
  - scipy=1.4
  - pandas=1.0
  - xarray=0.15
  - quaternion=2020.4.24.9.29.7
  - numba=0.48
  - anytree=2.8
  - pytest=5.4.3
  - pytest-cov=2.7.1
  - sphinx=2.4.4
  - sphinx_rtd_theme=0.4.3
  - numpydoc=0.9.1
  - coverage=4.5.3
  - bump2version=1.0.0
  - flake8=3.5.0
  - tox=3.5.2
  - ros-melodic-rospy=1.14.5 # [linux and x86_64]
  - ros-melodic-tf2-ros=0.6.5 # [linux and x86_64]
  - ros-melodic-geometry-msgs=1.12.7 # [linux and x86_64]
  - pykdl=1.4.0 # [linux and x86_64]
