{% set data = load_setup_py_data() %}

package:
  name: rigid-body-motion
  version: {{ data['version'] }}

source:
  path: ../..

build:
  noarch: python
  number: 6
  ignore_run_exports:
    - python_abi

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - quaternion
    - anytree

test:
  source_files:
    - tests
  requires:
    - python 3.6
    - pandas
    - xarray
    - netcdf4
    - numba
    - ipywidgets
    - ros-melodic-rospy # [linux and x86_64]
    - ros-melodic-tf # [linux and x86_64]
    - ros-melodic-tf2-ros # [linux and x86_64]
    - ros-melodic-tf2-geometry-msgs # [linux and x86_64]
    - ros-melodic-geometry-msgs # [linux and x86_64]
    - ros-melodic-visualization-msgs # [linux and x86_64]
    - ros-melodic-python-orocos-kdl # [linux and x86_64]
    - pytest
    - pytest-cov
  commands:
    - pytest --cov=rigid_body_motion

about:
  home: https://github.com/phausamann/rigid-body-motion
  summary: Python utilities for estimating and transforming rigid body motion.

extra:
  recipe-maintainers:
    - phausamann
