{% set data = load_setup_py_data() %}

package:
  name: rigid-body-motion
  version: {{ data['version'] }}

source:
  path: ../..

build:
  noarch: python
  number: 0
  ignore_run_exports:
    - python_abi

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - quaternion
    - anytree

test:
  source_files:
    - tests
  requires:
    - python 3.6
    - pandas
    - xarray
    - netcdf4
    - pooch
    - numba
    - ipywidgets
    - ros-noetic-rospy
    - ros-noetic-tf
    - ros-noetic-tf2-ros
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-visualization-msgs
    - python-orocos-kdl
    - boost=1.74
    - pytest
    - pytest-cov
  commands:
    - pytest --cov=rigid_body_motion

about:
  home: https://github.com/phausamann/rigid-body-motion
  summary: Python utilities for estimating and transforming rigid body motion.

extra:
  recipe-maintainers:
    - phausamann
