{% set data = load_setup_py_data() %}

package:
  name: rigid-body-motion
  version: {{ data['version'] }}

source:
  path: ../..

build:
  noarch: python
  number: 1
  string: py{{ python_version | replace('.', '') }}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - python {{ python_version }}
    - setuptools
  run:
    - python {{ python_version }}
    - numpy
    - scipy
    - quaternion
    - anytree

test:
  source_files:
    - tests
  requires:
    - python {{ python_version }}
    - numpy
    - pandas
    - xarray
    - scipy
    - quaternion
    - numba
    - anytree
    - ros-melodic-rospy # [py36 and linux and x86_64]
    - ros-melodic-tf2-ros # [py36 and linux and x86_64]
    - ros-melodic-geometry-msgs # [py36 and linux and x86_64]
    - pykdl 1.4.0 # [py36 and linux and x86_64]
    - pytest
  commands:
    - pytest

about:
  home: https://github.com/phausamann/rigid-body-motion
  summary: Python utilities for estimating and transforming rigid body motion.

extra:
  recipe-maintainers:
    - phausamann
