{% set version = "1.4.0" %}
{% set name = "pykdl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/orocos/orocos_kinematics_dynamics.git

build:
  skip: true  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make

  host:
    - python 3.6
    - eigen
    - pybind11

  run:
    - python 3.6

test:
  imports:
    - PyKDL

extra:
  recipe-maintainers:
    - phausamann
