name: rbm-ros
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - quaternion
  - numba
  - pytest
  - sip
  - sphinx=1.8.5
  - sphinx_rtd_theme
  - sphinx-gallery=0.4.0
  - numpydoc
  - pip:
    - rospkg
    - anytree
